<a href="https://colab.research.google.com/github/cyrinemimouni/ML/blob/main/TPpython1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
revenus = [1800, 1500, 1200, 1900, 2800, 2900, 4000]
print(revenus)
revenus_array = np.array(revenus)
revenus_array

[1800, 1500, 1200, 1900, 2800, 2900, 4000]


array([1800, 1500, 1200, 1900, 2800, 2900, 4000])

In [ ]:
i=2
j=8
p=1
np.arange(i, j, j)

array([2])

In [ ]:
np.linspace(i, j, 10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [ ]:
print(revenus_array[::-2])

[3000 1200 1800]


In [ ]:
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]

array([2800, 2900])

In [ ]:
revenus_array.mean()
revenus_array.max()
revenus_array.sort()
print (revenus_array)
revenus_array
revenus_array.sum()

[1200 1500 1800 1900 2800 2900 4000]


16100

In [ ]:
revenus_array[revenus_array > 2000] += 100
revenus_array

array([1200, 1500, 1800, 1900, 3800, 3900, 5000])

In [ ]:
hugo = [21,1400,0]
richard = [21,1400,0]
emilie = [21,1400,0]
tableau=[hugo,richard,emilie]

tab1 = np.array([[1,2],[3,4],[5,6]])
tab2 = np.array([[1,2,3],[4,5,6]])
print(tab1)
tab2

np.ones((3,5))
np.zeros((4,4))

np.random.random((6,3))

np.random.randint(1,10, size=(3,3))




[[1 2]
 [3 4]
 [5 6]]


array([[5, 9, 4],
       [7, 5, 6],
       [2, 5, 9]])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,10],[15,20]])
c=np.array([[2,4,6],[8,10,12]])

a+b

array([[ 6, 12],
       [18, 24]])

In [ ]:
a*b

array([[ 5, 20],
       [45, 80]])

In [ ]:
a@b

array([[ 35,  50],
       [ 75, 110]])